[workspace]

members = [
    "01_calories",
    "02_rock_paper_scissors",
    "03_rucksack_reorg",
    "04_camp_cleanup",
    "05_supply_stacks",
    "06_tuning_trouble",
    "07_no_space_left_on_device",
]
